name: CI MDO API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set SSH key
        run: |
             echo "$PRIVATE_KEY" > SSH_PRIVATE_KEY
             chmod 600 /home/master/.ssh/id_rsa
             env:
             PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Push to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22  
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
